C_RIME_CHAMELEON =  stack.c amodule.c c_channel.c
C_RIME_SINGLEHOP = c_abc.c c_broadcast.c c_unicast.c c_polite.c   
C_RIME_LQE = c_link_stats.c c_lqe_ewma.c c_lqe_wmewma.c c_lqe_ma.c c_lqe_linregr.c              
C_RIME_MULTIHOP  = c_route.c c_multihop.c c_netflood.c 
C_RIME_MESH      = c_route_discovery.c  c_mesh.c c_echo_app.c

CONTIKI_SOURCEFILES += $(C_RIME_SINGLEHOP) $(C_RIME_LQE) $(C_RIME_MULTIHOP) $(C_RIME_MESH) $(C_RIME_CHAMELEON)               
               
               
